//! Every game built from this engine. Each has a binary in `src/bin/` and a web
//! page generated by `scripts/web_html.py`.

use crate::core::modes::Mode;
use crate::core::scene::World;
use crate::game::GameConfig;

pub const GAMEMASH: GameConfig = GameConfig {
    title: "GameMash",
    tagline: "Eight game mechanics in one city, toggled live in any combination.",
    modes: None,
    world: None,
    night: None,
    help: &[],
};

/// Tribute to SkyCraft (Minecraft in Skyrim).
pub const BLOCKREALM: GameConfig = GameConfig {
    title: "Blockrealm",
    tagline: "A block-builder in an open-world RPG: mine, build and fight raiders across a voxel countryside.",
    modes: Some(&[Mode::Blocks]),
    world: Some(World::Realm),
    night: Some(false),
    help: &[
        "LMB: break blocks, or hit a raider in reach.  RMB: place.  Scroll: block type.  T: TNT.",
        "Melee: short reach, a swing cooldown, more knock-back when sprinting, critical hits while falling.",
        "Raiders guard the villages and the keep. Step back out of their wind-up.",
    ],
};

/// Tribute to ER Mario (Mario in Elden Ring).
pub const HOLLOW_WARDEN: GameConfig = GameConfig {
    title: "Hollow Warden",
    tagline: "A 3D platformer hero against a soulslike boss: jump its sweeps, break its posture, spin-throw it.",
    modes: Some(&[Mode::Jump]),
    world: Some(World::Arena),
    night: Some(false),
    help: &[
        "Jump the Warden's sweep, hop its shockwave, sidestep its charge. It gets faster below half health.",
        "Punches, dives, ground pounds and head stomps fill its posture. When it kneels, press E to grab, spin and throw it.",
        "Coins around the ring refill one wedge of your eight-wedge meter.",
    ],
};

/// Tribute to ArkWeb (web-swinging in a dark city).
pub const NIGHT_SWING: GameConfig = GameConfig {
    title: "Night Swing",
    tagline: "Web-swing through a moonlit city, steal cars out of the air and lose the police in the dark.",
    modes: Some(&[Mode::Streets, Mode::Swing]),
    world: Some(World::City),
    night: Some(true),
    help: &[
        "Steal a car within 2.5 s of a swing release for an AERIAL JACK.",
        "Crime raises your wanted level. Swing over roadblocks and lose the police in the dark.",
    ],
};

/// Tribute to the 2010 Rust Rewrite Mashup (a 2009 shooter, a 2010 skate sim and a block game).
pub const KICKFLIP_OPS: GameConfig = GameConfig {
    title: "Kickflip Ops",
    tagline: "A military shooter where you can drop onto a skateboard any time, in a city with a block quarry you can dig and build.",
    modes: Some(&[Mode::Skate, Mode::Warfare, Mode::Blocks]),
    world: Some(World::City),
    night: Some(false),
    help: &[
        "G: hop on or off the board.",
        "A kill within 1.5 s of a trick scores <TRICK> KILL. Explosions carve the block quarry; rail blocks are grindable.",
    ],
};

/// Tribute to the Minecraft-in-GTA V mods.
pub const BLOCK_CITY: GameConfig = GameConfig {
    title: "Block City",
    tagline: "An open-world crime city with a block-sandbox layer: steal cars, dig, build and blow up the streets.",
    modes: Some(&[Mode::Streets, Mode::Blocks]),
    world: Some(World::City),
    night: Some(false),
    help: &["TNT carves the city's block layer and wrecks cars. Wall off a street to stop a chase, or dig in while your wanted level climbs."],
};

pub const ALL: [&GameConfig; 6] = [&GAMEMASH, &BLOCKREALM, &HOLLOW_WARDEN, &NIGHT_SWING, &KICKFLIP_OPS, &BLOCK_CITY];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn locked_games_include_the_modes_their_world_needs() {
        for g in ALL {
            if let (Some(mask), Some(world)) = (g.locked(), g.world) {
                assert_eq!(mask & world.pinned(), world.pinned(), "{} locks out a mode {:?} needs", g.title, world);
            }
        }
    }

    #[test]
    fn locked_games_fix_their_whole_setup() {
        for g in ALL.iter().filter(|g| g.modes.is_some()) {
            assert!(g.world.is_some() && g.night.is_some() && !g.help.is_empty(), "{} leaves its setup to the URL", g.title);
        }
    }
}
